spring:
    application:
        name: auth
    cloud:
        nacos:
            discovery:
                server-addr: 172.19.0.40:8848
                username: nacos
                password: admin123
server:
    port: 28082