spring:
    application:
        name: gateway
    cloud:
        nacos:
            discovery:
                server-addr: 172.19.0.40:8848
                username: nacos
                password: admin123
        gateway:
            routes:
                - id: user_route
                  uri: lb://user
                  predicates:
                    - Path=/user/**
                  filters:
                    - StripPrefix=1
                - id: auth_route
                  uri: lb://auth
                  predicates:
                    - Path=/auth/**
                  filters:
                    - StripPrefix=1
server:
    port: 28080